# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai_server.grpc_impl import ai_llm_pb2 as ai__llm__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ai_llm_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LLMServiceStub(object):
    """============================================
    LLM Service (Qwen3-4B) - Port 50051
    자연어 처리 및 구조화된 작업 메시지 생성
    ============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseNaturalLanguage = channel.unary_unary(
            "/ai_llm.LLMService/ParseNaturalLanguage",
            request_serializer=ai__llm__pb2.NLRequest.SerializeToString,
            response_deserializer=ai__llm__pb2.StructuredResponse.FromString,
            _registered_method=True,
        )


class LLMServiceServicer(object):
    """============================================
    LLM Service (Qwen3-4B) - Port 50051
    자연어 처리 및 구조화된 작업 메시지 생성
    ============================================
    """

    def ParseNaturalLanguage(self, request, context):
        """자연어 프롬프트 해석 (구조화된 작업 메시지로 변환)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ParseNaturalLanguage": grpc.unary_unary_rpc_method_handler(
            servicer.ParseNaturalLanguage,
            request_deserializer=ai__llm__pb2.NLRequest.FromString,
            response_serializer=ai__llm__pb2.StructuredResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ai_llm.LLMService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ai_llm.LLMService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """============================================
    LLM Service (Qwen3-4B) - Port 50051
    자연어 처리 및 구조화된 작업 메시지 생성
    ============================================
    """

    @staticmethod
    def ParseNaturalLanguage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ai_llm.LLMService/ParseNaturalLanguage",
            ai__llm__pb2.NLRequest.SerializeToString,
            ai__llm__pb2.StructuredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
