# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_vision.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61i_vision.proto\x12\tai_vision\"\x07\n\x05\x45mpty\"H\n\x0cImageRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x17\n\nimage_data\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\r\n\x0b_image_data\"g\n\x17ObjectDetectionResponse\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12#\n\x03\x62ox\x18\x03 \x01(\x0b\x32\x16.ai_vision.BoundingBox\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"l\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x13\n\x0bperson_type\x18\x01 \x01(\t\x12\x18\n\x0b\x65mployee_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x42\x0e\n\x0c_employee_id\"S\n\x1cMultiObjectDetectionResponse\x12\x33\n\x07objects\x18\x01 \x03(\x0b\x32\".ai_vision.ObjectDetectionResponse\"\xff\x01\n\x0cVisionResult\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12>\n\x10object_detection\x18\x03 \x01(\x0b\x32\".ai_vision.ObjectDetectionResponseH\x00\x12>\n\x10\x66\x61\x63\x65_recognition\x18\x04 \x01(\x0b\x32\".ai_vision.FaceRecognitionResponseH\x00\x12@\n\rmulti_objects\x18\x05 \x01(\x0b\x32\'.ai_vision.MultiObjectDetectionResponseH\x00\x42\x08\n\x06result2\xcb\x02\n\rVisionService\x12L\n\rDetectObjects\x12\x17.ai_vision.ImageRequest\x1a\".ai_vision.ObjectDetectionResponse\x12M\n\x0eRecognizeFaces\x12\x17.ai_vision.ImageRequest\x1a\".ai_vision.FaceRecognitionResponse\x12Y\n\x15\x44\x65tectMultipleObjects\x12\x17.ai_vision.ImageRequest\x1a\'.ai_vision.MultiObjectDetectionResponse\x12\x42\n\x13StreamVisionResults\x12\x10.ai_vision.Empty\x1a\x17.ai_vision.VisionResult0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_IMAGEREQUEST']._serialized_start=39
  _globals['_IMAGEREQUEST']._serialized_end=111
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_start=113
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_end=216
  _globals['_BOUNDINGBOX']._serialized_start=218
  _globals['_BOUNDINGBOX']._serialized_end=284
  _globals['_FACERECOGNITIONRESPONSE']._serialized_start=286
  _globals['_FACERECOGNITIONRESPONSE']._serialized_end=394
  _globals['_MULTIOBJECTDETECTIONRESPONSE']._serialized_start=396
  _globals['_MULTIOBJECTDETECTIONRESPONSE']._serialized_end=479
  _globals['_VISIONRESULT']._serialized_start=482
  _globals['_VISIONRESULT']._serialized_end=737
  _globals['_VISIONSERVICE']._serialized_start=740
  _globals['_VISIONSERVICE']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
