# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from main_server.infrastructure.grpc import ai_inference_pb2 as main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in main_server/infrastructure/grpc/ai_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """============================================
    LLM Service (Qwen3-4B) - Port 50051
    ============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/ai_inference.LLMService/GenerateText',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextRequest.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ai_inference.LLMService/Chat',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ChatRequest.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.AnalyzeIntent = channel.unary_unary(
                '/ai_inference.LLMService/AnalyzeIntent',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextRequest.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.IntentResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """============================================
    LLM Service (Qwen3-4B) - Port 50051
    ============================================
    """

    def GenerateText(self, request, context):
        """텍스트 생성
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """대화형 응답
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeIntent(self, request, context):
        """의도 분석
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextRequest.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ChatRequest.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ChatResponse.SerializeToString,
            ),
            'AnalyzeIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeIntent,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextRequest.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.IntentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_inference.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_inference.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """============================================
    LLM Service (Qwen3-4B) - Port 50051
    ============================================
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.LLMService/GenerateText',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextRequest.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.LLMService/Chat',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ChatRequest.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.LLMService/AnalyzeIntent',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.TextRequest.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.IntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VisionServiceStub(object):
    """============================================
    Vision Service (YOLOv8n) - Port 50052
    ============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObjects = channel.unary_unary(
                '/ai_inference.VisionService/DetectObjects',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ObjectDetectionResponse.FromString,
                _registered_method=True)
        self.RecognizeFaces = channel.unary_unary(
                '/ai_inference.VisionService/RecognizeFaces',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.FaceRecognitionResponse.FromString,
                _registered_method=True)
        self.DetectMultipleObjects = channel.unary_unary(
                '/ai_inference.VisionService/DetectMultipleObjects',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.MultiObjectDetectionResponse.FromString,
                _registered_method=True)
        self.StreamVisionResults = channel.unary_stream(
                '/ai_inference.VisionService/StreamVisionResults',
                request_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.Empty.SerializeToString,
                response_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.VisionResult.FromString,
                _registered_method=True)


class VisionServiceServicer(object):
    """============================================
    Vision Service (YOLOv8n) - Port 50052
    ============================================
    """

    def DetectObjects(self, request, context):
        """객체 인식
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFaces(self, request, context):
        """얼굴 인식
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectMultipleObjects(self, request, context):
        """복수 객체 인식
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVisionResults(self, request, context):
        """실시간 비전 스트리밍
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObjects,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ObjectDetectionResponse.SerializeToString,
            ),
            'RecognizeFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFaces,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.FaceRecognitionResponse.SerializeToString,
            ),
            'DetectMultipleObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectMultipleObjects,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.MultiObjectDetectionResponse.SerializeToString,
            ),
            'StreamVisionResults': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVisionResults,
                    request_deserializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.Empty.FromString,
                    response_serializer=main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.VisionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_inference.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_inference.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService(object):
    """============================================
    Vision Service (YOLOv8n) - Port 50052
    ============================================
    """

    @staticmethod
    def DetectObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.VisionService/DetectObjects',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ObjectDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.VisionService/RecognizeFaces',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.FaceRecognitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectMultipleObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.VisionService/DetectMultipleObjects',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.ImageRequest.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.MultiObjectDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVisionResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_inference.VisionService/StreamVisionResults',
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.Empty.SerializeToString,
            main__server_dot_infrastructure_dot_grpc_dot_ai__inference__pb2.VisionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
