# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_llm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61i_llm.proto\x12\x06\x61i_llm\",\n\tNLRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x08ItemInfo\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x9e\x01\n\x12StructuredResponse\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12#\n\ttask_type\x18\x02 \x01(\x0e\x32\x10.ai_llm.TaskType\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12-\n\nstruct_msg\x18\x04 \x01(\x0b\x32\x19.ai_llm.StructuredMessage\x12\x10\n\x08raw_text\x18\x05 \x01(\t\"\xf6\x02\n\x11StructuredMessage\x12\x15\n\x08location\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0erequester_name\x18\n \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rreceiver_name\x18\x0b \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0cvisitor_name\x18\x0c \x01(\tH\x03\x88\x01\x01\x12\x1c\n\x0fsource_location\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1a\n\rdest_location\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x1f\n\x05items\x18\x07 \x03(\x0b\x32\x10.ai_llm.ItemInfo\x12\x14\n\x07message\x18\x13 \x01(\tH\x06\x88\x01\x01\x12\x10\n\x08keywords\x18\x14 \x03(\tB\x0b\n\t_locationB\x11\n\x0f_requester_nameB\x10\n\x0e_receiver_nameB\x0f\n\r_visitor_nameB\x12\n\x10_source_locationB\x10\n\x0e_dest_locationB\n\n\x08_message*s\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0eSNACK_DELIVERY\x10\x01\x12\x11\n\rITEM_DELIVERY\x10\x02\x12\x0f\n\x0bGUIDE_GUEST\x10\x03\x12\x14\n\x10GENERAL_QUESTION\x10\x46\x12\x0c\n\x08GREETING\x10G2S\n\nLLMService\x12\x45\n\x14ParseNaturalLanguage\x12\x11.ai_llm.NLRequest\x1a\x1a.ai_llm.StructuredResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_llm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKTYPE._serialized_start=657
  _TASKTYPE._serialized_end=772
  _NLREQUEST._serialized_start=24
  _NLREQUEST._serialized_end=68
  _ITEMINFO._serialized_start=70
  _ITEMINFO._serialized_end=117
  _STRUCTUREDRESPONSE._serialized_start=120
  _STRUCTUREDRESPONSE._serialized_end=278
  _STRUCTUREDMESSAGE._serialized_start=281
  _STRUCTUREDMESSAGE._serialized_end=655
  _LLMSERVICE._serialized_start=774
  _LLMSERVICE._serialized_end=857
# @@protoc_insertion_point(module_scope)
