office_robot_executor:
  ros__parameters:
    robot_name: robot_1
    robot_id: 1
    mock_mode: false
    use_nav2: true
    execution_delay_sec: 1.5
    nav2_action_name: navigate_to_pose
    frame_id: map
    goal_timeout_sec: 60.0
    stop_cmd_vel_topic: cmd_vel
    stop_publish_count: 10
    stop_publish_hz: 20.0
    safety_lock_topic: safety_lock
    ai_link_topic: ai_link
    include_ai_link_in_status: true
